name: 'Terraform'

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]


jobs:
  terraform_test:
    name: 'Terraform Test'
    runs-on: ubuntu-latest
    container:
      image: node:latest
      ports:
        - 8000:8000
    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: ${{ vars.USER }}
          POSTGRES_PASSWORD: ${{ secrets.PASS }}
          POSTGRES_DB: ${{ vars.DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432

    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.21
      id: go
  
  
