name: 'Terraform'

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

env:
  MY_USER: ${{ vars.USER }}
  MY_PASS: ${{ secrets.PASS }}
  MY_DB: ${{ vars.DB }}
jobs:
  terraform_test:
    name: 'Terraform Test'
    runs-on: ubuntu-latest
    steps:
    - name: Setup Postgres
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql postgresql-contrib -y
        sleep 10
        sudo systemctl start postgresql.service
    - name: Create db
      run : |
        sudo su postgres <<EOF
        createdb ${{ vars.DB }}
        psql -c "CREATE ROLE ${{ vars.USER }} WITH LOGIN PASSWORD '${{ secrets.PASSWORD}}';"
        EOF
  
  
