name: 'Terraform'

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

env:
  MY_USER: ${{ vars.USER }}
  MY_PASS: ${{ secrets.PASS }}
  MY_DB: ${{ vars.DB }}
jobs:
  terraform_test:
    name: 'Terraform Test'
    runs-on: ubuntu-latest
    steps:
    - name: Setup Postgres
      run: |
        sudo apt-get update
        sudo apt-get install -y postgres-client
    - name: Create db
      run : |
        psql -h localhost -U ${{ vars.USER }} -c "CREATE DATABASE ${{ vars.DB }}"
  
  
